context:
  version: 2.6.2.post0

package:
  name: pybind11_mkdoc
  version: ${{ version }}

source:
- path: ../
# - git: https://github.com/peter-urban/pybind11_mkdoc.git
#   branch: libclang

build:
  script: ${{ PYTHON }} -m pip install .
  python:
    entry_points:
    - pybind11-mkdoc = pybind11_mkdoc:main
  noarch: python

requirements:
  host:
  - python >=3.11
  - flit-core >=2,<4
  - pip
  run:
  - python >=3.11
  - python-clang

tests:
- python:
    imports:
    - pybind11_mkdoc
    pip_check: false
- script:
    - pytest -v tests/ #--ignore=tests/long_parameter_test.py --timeout=5
  requirements:
    run:
    - pytest
    - pytest-timeout
    - pybind11
    - libclang
  files:
    source:
    - tests/

about:
  homepage: https://github.com/pybind/pybind11_mkdoc
  summary: This is a package for building pybind11 docstrings from C++ header comments.
  description: ''
  license: MIT
